package projeto_biblioteca.Interface;

public enum Etapas {
	PEDINDO_LOGIN,
	COLETANDO_LOGIN,
	RECEBENDO_MENU_CLIENTE,
	RECEBENDO_MENU_OPERADOR,
	CADASTRANDO_LIVRO,
	EDITANDO_LIVRO,
	REMOVENDO_LIVRO,
	CADASTRAR_CLIENTE,
	REMOVER_CLIENTE
}
